name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  PRINCIPIA_HEADERS_GLOG: src/**/*.h
  PRINCIPIA_MSVC_GLOG: msvc

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          configuration: [Debug, Release]
    steps:
    - name: Checkout source files
      uses: actions/checkout@v3

    - name: Trace
      run: |
        echo ${{ github.workspace }}
        tree /f .
      shell: pwsh

    - name: Download chromium artifacts
      uses: mockingbirdnest/actions/windows/download_artifact@WF
      with:
        name: chromium

    - name: Find MSBuild
      uses: mockingbirdnest/actions/windows/find_msbuild@main

    - name: Rebuild ${{ matrix.configuration }}
      uses: mockingbirdnest/actions/windows/rebuild@main
      with:
        configuration: ${{ matrix.configuration }}
        solution_directory: ${{ env.PRINCIPIA_MSVC_GLOG }}

    - name: Upload artifact
      uses: mockingbirdnest/actions/windows/upload_artifact@main
      with:
        name: glog
        headers_glob: ${{ env.PRINCIPIA_HEADERS_GLOG }}
        solution_directory: ${{ env.PRINCIPIA_MSVC_GLOG }}
