name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  PRINCIPIA_HEADERS_GLOG: src
  PRINCIPIA_MSVC_GLOG: msvc

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          configuration: [Debug, Release]
    steps:
    - name: Checkout source files
      uses: actions/checkout@v3

    - name: Download chromium artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ github.token }}
        workflow: build.yaml
        workflow_conclusion: success
        name: chromium
        path: ${{ github.workspace }}/chromium
        repo: mockingbirdnest/chromium

    - name: Initialize build environment
      uses: mockingbirdnest/actions/windows/initialize_build@WF
      with:
        configuration: ${{ matrix.configuration }}

    - name: Rebuild ${{ matrix.configuration }}
      uses: mockingbirdnest/actions/windows/rebuild@main
      with:
        configuration: ${{ matrix.configuration }}
        solution_directory: ${{ env.PRINCIPIA_MSVC_GLOG }}

    - name: Upload artifact
      uses: mockingbirdnest/actions/windows/upload_artifact@WF
      with:
        name: glog
        headers_directory: ${{ env.PRINCIPIA_HEADERS_GLOG }}
        solution_directory: ${{ env.PRINCIPIA_MSVC_GLOG }}
